project:
  type: website
  output-dir: docs

website:
  title: ""
  twitter-card: true
  navbar:
    title: false
    right:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: CV.qmd
        text: CV
    left: 
      - icon: github
        href: https://github.com/albertoventurin
      - icon: twitter
        href: https://twitter.com/albe_venturin
      - icon: envelope
        href: mailto:alberto.venturin@eui.eu
      - icon: linkedin
        href: https://www.linkedin.com/in/alberto-venturin/
        

format:
  html:
    theme: 
      dark: theme-dark.scss
      light: theme-light.scss
    css: styles.css
    toc: true



